// 项目路由表：
let navMap = [{
    "children": [{
        "children": [{
                "children": [],
                "href": "/menu/list",
                "icon": "",
                "id": "1-1-1",
                "index": "1-1-1", 
                "parentId": 37,
                "permission": "permission:assign",
                "description": "",
                "sort": 1,
                "source": 1,
                "status": 0,
                "title": "菜单管理",
                "type": 1
            },
            {
                "children": [],
                "href": "/menu/roles",
                "icon": "",
                "id": "1-1-2",
                "index": "1-1-2", 
                "parentId": 37,
                "permission": "permission:assign",
                "description": "",
                "sort": 2,
                "source": 1,
                "status": 0,
                "title": "角色管理",
                "type": 1
            }
        ],
        "href": "",
        "icon": "",
        "id": "1-1",
        "index": "1-1", 
        "parentId": 1,
        "permission": "",
        "description": "",
        "sort": 1,
        "source": 1,
        "status": 0,
        "title": "系统指派",
        "type": 1
    }],
    "href": "",
    "icon": "el-icon-monitor",
    "id": 1,
    "index": "1", 
    "parentId": 0,
    "permission": "",
    "description": "",
    "sort": 1,
    "source": 1,
    "status": 0,
    "title": "系统设置admin",
    "type": 1
},
{
    "href": "/monitor",
    "path": "/monitor",
    "meta": {},
    "icon": "el-icon-monitor",
    "id": 2,
    "index": "2", 
    "parentId": 0,
    "permission": "",
    "description": "",
    "sort": 2,
    "source": 1,
    "status": 0,
    "title": "大屏监控",
    "type": 1
}]